### ISSUE TITLE
Can't start the development server

### ISSUE THREAD

**Issue by owakethm** [simon300000/musedash.moe#10]
When I try to setup the developer, I first type

`npm install`
When I do that I get 

>  jules@eucalyptus  ~/WSoftware/musedash.moe   master  npm install 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
> 
> audited 37867 packages in 5.013s
found 0 vulnerabilities

and when I try to `npm run serve`
I get the error:

>  ERROR  Failed to compile with 6 errors
These dependencies were not found: 
> 
> To install them, you can run: npm install --save @/components/vue-octicon/src/components/Octicon.vue @/components/vue-octicon/src/icons/device-desktop @/components/vue-octicon/src/icons/device-mobile

But it still returning an error that the package doesn't exist or can't find package.json in it.

**Comment by simon300000** [comment]
Oh sorry I forgot some command
```sh
git submodule init
git submodule update
```

**Comment by simon300000** [comment]
If you want to use a different API server, this could be configured here
<img width="751" alt="image" src="https://user-images.githubusercontent.com/12656264/67738981-09f5c300-fa11-11e9-9b96-f727b9c1d75e.png">

Or at
https://github.com/simon300000/musedash.moe/blob/master/src/api.js#L4
