### ISSUE TITLE
Something in Relative Difficulty broke

### ISSUE THREAD

**Issue by rosemagwin** [simon300000/musedash.moe#255]
15 songs are now on the top of the relative difficulty chart. Looks like some math shat the bed.

![image](https://user-images.githubusercontent.com/108752795/190974019-dbbca298-0f01-44cf-b3a2-058e7ba9d132.png)

As much as I enjoy now being considered 12 in the relative difficulty department, I dont think it's correct, lol.

**Comment by simon300000** [comment]
Yes this is a known issue, I guess it is some kind of divide by 0 issue, and it kinda goes away after a day

**Comment by simon300000** [comment]
I haven’t fixed it because it literally occurs once a year, but seems like I do need to fix it

**Comment by simon300000** [comment]
found the problem.
Some bad number wasn't filtered
https://web.archive.org/web/20220921071617/https://musedash.moe/player/5f0442f0ae6511eaaf310242ac110010
<img width="1353" alt="image" src="https://user-images.githubusercontent.com/12656264/191439505-a1ae1414-46ba-4767-a04a-171da6e6fde8.png">

**Comment by simon300000** [comment]
Should be fixed
