### ISSUE TITLE
Website cannot be installed as a PWA

### ISSUE THREAD

**Issue by wpcwzy** [simon300000/musedash.moe#264]
This website cannot be installed as a PWA since the PWA will automatically request [https://musedash.moe/index.html](https://musedash.moe/index.html) and get a "Not Found" response.
![image](https://user-images.githubusercontent.com/16263217/200453264-e32e696d-73d5-450e-a701-72a4f9027d0e.png)
You can reproduce the problem by clicking "Open in Microsoft Edge" and check the URL it request.
![image](https://user-images.githubusercontent.com/16263217/200453911-6b55fcb2-4e73-4f4f-96bd-aeec306054b9.png)
![image](https://user-images.githubusercontent.com/16263217/200453575-59249acd-dfdb-43db-bbeb-703812a2a22b.png)
My system environment:
Windows 11 22H2 (22621.755) + Microsoft Edge 106.0.1370.47

**Comment by simon300000** [comment]
修好了

**Comment by wpcwzy** [comment]
感谢！
